In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['absolute_error', 'poisson', 'squared_error', 'friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['absolute_error', 'poisson',
                                       'squared_error', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100}:

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.284622,0.004042,0.005989,0.001193,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",0.820819,0.770764,0.846157,0.812791,0.825130,0.815132,0.024774,22
1,2.768652,0.017917,0.022706,0.002356,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.832690,0.769441,0.847348,0.821899,0.835356,0.821347,0.027187,14
2,0.172650,0.012798,0.005115,0.000205,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.845333,0.764234,0.845923,0.801518,0.834410,0.818284,0.031490,16
3,1.655057,0.029746,0.023651,0.002365,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856785,0.779148,0.854661,0.829112,0.842394,0.832420,0.028413,7
4,0.172921,0.008111,0.005008,0.000010,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.851928,0.754088,0.840101,0.815153,0.828719,0.817998,0.034197,17
5,1.638760,0.021274,0.021572,0.001325,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.859993,0.777322,0.855046,0.827522,0.850262,0.834029,0.030455,3
6,0.081888,0.002694,0.004800,0.000399,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",0.831704,0.760411,0.836784,0.813867,0.804869,0.809527,0.027158,24
7,0.772181,0.007397,0.022666,0.000525,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",0.846967,0.773585,0.853293,0.818356,0.836399,0.825720,0.028629,11
8,0.064222,0.001974,0.005400,0.000490,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.846354,0.765160,0.857033,0.820466,0.832997,0.824402,0.032080,12
9,0.579863,0.009438,0.024032,0.001226,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.857764,0.778306,0.861792,0.829909,0.842532,0.834061,0.030095,2
10,0.061017,0.000363,0.004991,0.000022,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.845313,0.737564,0.849071,0.806729,0.835338,0.814803,0.041371,23
11,0.596107,0.009289,0.023852,0.001830,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.854716,0.781503,0.857817,0.829836,0.840828,0.832940,0.027607,5
12,0.078041,0.003539,0.005420,0.000515,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",0.851003,0.790139,0.833142,0.815743,0.822036,0.822413,0.020094,13
13,0.682895,0.004240,0.021970,0.000614,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.849311,0.774388,0.859662,0.816212,0.838607,0.827636,0.030271,9
14,0.055710,0.000981,0.005199,0.000399,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.849132,0.772439,0.835829,0.819091,0.816825,0.818663,0.025936,15
15,0.522391,0.005946,0.022931,0.000366,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.856329,0.777350,0.861302,0.830773,0.836586,0.832468,0.029862,6
16,0.054564,0.000670,0.004800,0.000400,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.844802,0.761109,0.842983,0.805906,0.823794,0.815719,0.030766,21
17,0.533726,0.007325,0.024344,0.003040,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.859557,0.779513,0.861951,0.826283,0.839409,0.833342,0.029966,4
18,0.077710,0.003249,0.005559,0.000405,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.834770,0.754158,0.846691,0.814493,0.829936,0.816010,0.032604,20
19,0.682258,0.008384,0.022835,0.002200,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.848190,0.771448,0.857265,0.816264,0.837878,0.826209,0.030599,10
20,0.057722,0.002032,0.005202,0.000400,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.841682,0.756497,0.837211,0.825032,0.821336,0.816351,0.030853,19
21,0.510413,0.010415,0.021476,0.002999,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.855935,0.777486,0.860427,0.826436,0.839251,0.831907,0.029787,8
22,0.057115,0.003655,0.005439,0.000487,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.838640,0.768287,0.837054,0.811786,0.829108,0.816975,0.026143,18
23,0.440748,0.013486,0.016288,0.002307,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.862770,0.778513,0.862282,0.830231,0.840673,0.834894,0.030858,1

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:34
BMI:45
Children:1
Sex Male 0 or 1:0
Smoker Yes 0 or 1:0

In [14]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[6353.0905304]

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(